export const mockSearch = [
  { id: 1, term: "Super Bowl LX"},
  { id: 2, term: "OpenAI"},
  { id: 3, term: "Taylor Swift"},
  { id: 4, term: "Winter Olympics 2026"},
  { id: 5, term: "Donald Trump"},
  { id: 6, term: "Elon Musk"},
  { id: 7, term: "Billie Eilish"},
  { id: 8, term: "Puppy Bowl XXII"},
  { id: 9, term: "World Cup 2026"},
  { id: 10, term: "Apple Inc."},
  { id: 11, term: "Amazon"},
  { id: 12, term: "Bitcoin"},
  { id: 13, term: "Meta"},
  { id: 14, term: "Steam Deck"},
  { id: 15, term: "Steph Curry"},
  { id: 16, term: "S&P 500"},
  { id: 17, term: "Tesla"},
  { id: 18, term: "iPhone 18 Pro"},
  { id: 19, term: "Quantum Computing"},
  { id: 20, term: "Lebron James"},
  { id: 21, term: "Venmo"},
];